//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kishan_bot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be some issue. I request you to Check your internet connection, then Refresh the session by clicking the refresh button at the bottom left corner, and then try again..
        /// </summary>
        public static string error_default_message {
            get {
                return ResourceManager.GetString("error.default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are disconnected. Please refresh or login again..
        /// </summary>
        public static string error_disconnected {
            get {
                return ResourceManager.GetString("error.disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type or select a message to send..
        /// </summary>
        public static string error_empty_msg {
            get {
                return ResourceManager.GetString("error.empty_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit rating..
        /// </summary>
        public static string error_fail_to_submit {
            get {
                return ResourceManager.GetString("error.fail_to_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit review..
        /// </summary>
        public static string error_fail_to_submit_review {
            get {
                return ResourceManager.GetString("error.fail_to_submit_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP not sent.
        /// </summary>
        public static string error_otp_not_sent {
            get {
                return ResourceManager.GetString("error.otp_not_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending OTP.
        /// </summary>
        public static string error_sending_otp {
            get {
                return ResourceManager.GetString("error.sending_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID not registered..
        /// </summary>
        public static string error_userid_not_registered {
            get {
                return ResourceManager.GetString("error.userid_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for reply..
        /// </summary>
        public static string error_wait_new_chat {
            get {
                return ResourceManager.GetString("error.wait_new_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string label_back {
            get {
                return ResourceManager.GetString("label.back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string label_chats {
            get {
                return ResourceManager.GetString("label.chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string label_click {
            get {
                return ResourceManager.GetString("label.click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string label_close {
            get {
                return ResourceManager.GetString("label.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this conversation?.
        /// </summary>
        public static string label_confirm_delete {
            get {
                return ResourceManager.GetString("label.confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string label_continue {
            get {
                return ResourceManager.GetString("label.continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial.
        /// </summary>
        public static string label_dial {
            get {
                return ResourceManager.GetString("label.dial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string label_examples {
            get {
                return ResourceManager.GetString("label.examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Worker.
        /// </summary>
        public static string label_extension_worker {
            get {
                return ResourceManager.GetString("label.extension_worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string label_faqs {
            get {
                return ResourceManager.GetString("label.faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        public static string label_farmer {
            get {
                return ResourceManager.GetString("label.farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string label_feedback {
            get {
                return ResourceManager.GetString("label.feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string label_logout {
            get {
                return ResourceManager.GetString("label.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string label_mobile_number {
            get {
                return ResourceManager.GetString("label.mobile_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string label_more {
            get {
                return ResourceManager.GetString("label.more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat.
        /// </summary>
        public static string label_new_chat {
            get {
                return ResourceManager.GetString("label.new_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string label_next {
            get {
                return ResourceManager.GetString("label.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string label_no {
            get {
                return ResourceManager.GetString("label.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Chats.
        /// </summary>
        public static string label_no_history {
            get {
                return ResourceManager.GetString("label.no_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Beneficiary, Thank for reaching out to us with your query. In order to provide you with the correct resolution, we kindly request you to provide us with your Aadhaar Number / PM KISAN ID / Phone no..
        /// </summary>
        public static string label_popUpTitle {
            get {
                return ResourceManager.GetString("label.popUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last 4 digits of Aadhaar.
        /// </summary>
        public static string label_popUpTitle2 {
            get {
                return ResourceManager.GetString("label.popUpTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Beneficiary, request you to kindly enter the OTP that has been received by you..
        /// </summary>
        public static string label_popUpTitle3 {
            get {
                return ResourceManager.GetString("label.popUpTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string label_previous {
            get {
                return ResourceManager.GetString("label.previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string label_profile {
            get {
                return ResourceManager.GetString("label.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string label_search {
            get {
                return ResourceManager.GetString("label.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string label_send {
            get {
                return ResourceManager.GetString("label.send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisan e-Mitra.
        /// </summary>
        public static string label_splash_title {
            get {
                return ResourceManager.GetString("label.splash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string label_submit {
            get {
                return ResourceManager.GetString("label.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string label_submit_review {
            get {
                return ResourceManager.GetString("label.submit_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisan-eMitra.
        /// </summary>
        public static string label_title {
            get {
                return ResourceManager.GetString("label.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string label_welcome {
            get {
                return ResourceManager.GetString("label.welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string label_yes {
            get {
                return ResourceManager.GetString("label.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also change your language from here..
        /// </summary>
        public static string message_app_tour_alternate_language_selection_description {
            get {
                return ResourceManager.GetString("message.app_tour_alternate_language_selection_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Sound&quot; icon to listen to information..
        /// </summary>
        public static string message_app_tour_audio_button_description {
            get {
                return ResourceManager.GetString("message.app_tour_audio_button_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Tutorial.
        /// </summary>
        public static string message_app_tour_exit {
            get {
                return ResourceManager.GetString("message.app_tour_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language from the menu.
        /// </summary>
        public static string message_app_tour_language_selection_description {
            get {
                return ResourceManager.GetString("message.app_tour_language_selection_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the &quot;Mic&quot; icon to record your message and tap it again to stop..
        /// </summary>
        public static string message_app_tour_mic_button_description {
            get {
                return ResourceManager.GetString("message.app_tour_mic_button_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Refresh&quot; to reload the page.
        /// </summary>
        public static string message_app_tour_refresh_button_description {
            get {
                return ResourceManager.GetString("message.app_tour_refresh_button_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these example questions for help.
        /// </summary>
        public static string message_app_tour_sample_questions_description {
            get {
                return ResourceManager.GetString("message.app_tour_sample_questions_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press this Arrow button to send your message..
        /// </summary>
        public static string message_app_tour_send_button_description {
            get {
                return ResourceManager.GetString("message.app_tour_send_button_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your questions here..
        /// </summary>
        public static string message_app_tour_typebox_description {
            get {
                return ResourceManager.GetString("message.app_tour_typebox_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next below to proceed or Click Exit Tutorial to skip the manual tutorial.
        /// </summary>
        public static string message_app_tour_welcome_description {
            get {
                return ResourceManager.GetString("message.app_tour_welcome_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Kisan-eMitra User Manual.
        /// </summary>
        public static string message_app_tour_welcome_header {
            get {
                return ResourceManager.GetString("message.app_tour_welcome_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Your Question.
        /// </summary>
        public static string message_ask_ur_question {
            get {
                return ResourceManager.GetString("message.ask_ur_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot answer again.
        /// </summary>
        public static string message_cannot_answer_again {
            get {
                return ResourceManager.GetString("message.cannot_answer_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon!.
        /// </summary>
        public static string message_coming_soon {
            get {
                return ResourceManager.GetString("message.coming_soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are going to launch this feature very soon. Stay tuned!.
        /// </summary>
        public static string message_coming_soon_description {
            get {
                return ResourceManager.GetString("message.coming_soon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation!.
        /// </summary>
        public static string message_confirmation {
            get {
                return ResourceManager.GetString("message.confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect with call centre.
        /// </summary>
        public static string message_dial_description {
            get {
                return ResourceManager.GetString("message.dial_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may speak to an Ama Krushi expert to get a satisfactory response.
        /// </summary>
        public static string message_dialer_popup {
            get {
                return ResourceManager.GetString("message.dialer_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive the OTP?.
        /// </summary>
        public static string message_didnt_receive {
            get {
                return ResourceManager.GetString("message.didnt_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string message_down_time_retry {
            get {
                return ResourceManager.GetString("message.down_time_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        public static string message_enter_mobile {
            get {
                return ResourceManager.GetString("message.enter_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is my money?.
        /// </summary>
        public static string message_example_ques_one {
            get {
                return ResourceManager.GetString("message.example_ques_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whom do I need to speak to in order to get my money?.
        /// </summary>
        public static string message_example_ques_three {
            get {
                return ResourceManager.GetString("message.example_ques_three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the status of my application?.
        /// </summary>
        public static string message_example_ques_two {
            get {
                return ResourceManager.GetString("message.example_ques_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was this helpful?.
        /// </summary>
        public static string message_helpful {
            get {
                return ResourceManager.GetString("message.helpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a 10 digit number!.
        /// </summary>
        public static string message_invalid_mobile {
            get {
                return ResourceManager.GetString("message.invalid_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Otp.
        /// </summary>
        public static string message_invalid_otp {
            get {
                return ResourceManager.GetString("message.invalid_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for selecting the English language.
        ///Dear Beneficiary,
        ///Type your question or speak using the mic button. Just touch the mic button and say your question. Touch the mic button again to stop recording..
        /// </summary>
        public static string message_language_changed_greeting {
            get {
                return ResourceManager.GetString("message.language_changed_greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry for any trouble. I&apos;m getting updated and fixing some issues to assist you better. I will be available again soon. Please come back and try again after some time..
        /// </summary>
        public static string message_maintenance_mode_body {
            get {
                return ResourceManager.GetString("message.maintenance_mode_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll be back soon!.
        /// </summary>
        public static string message_maintenance_mode_header {
            get {
                return ResourceManager.GetString("message.maintenance_mode_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Chat History with AI will come here.
        /// </summary>
        public static string message_no_history {
            get {
                return ResourceManager.GetString("message.no_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered yet ?.
        /// </summary>
        public static string message_not_register_yet {
            get {
                return ResourceManager.GetString("message.not_register_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you a one time password on this.
        /// </summary>
        public static string message_otp_message {
            get {
                return ResourceManager.GetString("message.otp_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp not sent.
        /// </summary>
        public static string message_otp_not_sent {
            get {
                return ResourceManager.GetString("message.otp_not_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent again.
        /// </summary>
        public static string message_otp_sent_again {
            get {
                return ResourceManager.GetString("message.otp_sent_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OTP Verification.
        /// </summary>
        public static string message_otp_verification {
            get {
                return ResourceManager.GetString("message.otp_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have not received my last instalment payment..
        /// </summary>
        public static string message_popular_question_1 {
            get {
                return ResourceManager.GetString("message.popular_question_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me the status of my PM Kisan account.
        /// </summary>
        public static string message_popular_question_2 {
            get {
                return ResourceManager.GetString("message.popular_question_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the issue with my PM KISAN account?.
        /// </summary>
        public static string message_popular_question_3 {
            get {
                return ResourceManager.GetString("message.popular_question_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why am I not an eligible beneficiary?.
        /// </summary>
        public static string message_popular_question_4 {
            get {
                return ResourceManager.GetString("message.popular_question_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you find this useful?.
        /// </summary>
        public static string message_rating {
            get {
                return ResourceManager.GetString("message.rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a star to rate.
        /// </summary>
        public static string message_rating_description {
            get {
                return ResourceManager.GetString("message.rating_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Submitted!.
        /// </summary>
        public static string message_rating_submitted {
            get {
                return ResourceManager.GetString("message.rating_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is an issue processing your request at the moment. Please try again later..
        /// </summary>
        public static string message_recorder_error {
            get {
                return ResourceManager.GetString("message.recorder_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your request....
        /// </summary>
        public static string message_recorder_wait {
            get {
                return ResourceManager.GetString("message.recorder_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register at Krushak Odisha.
        /// </summary>
        public static string message_register_at_krushak {
            get {
                return ResourceManager.GetString("message.register_at_krushak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are already registered then use your mobile number to login..
        /// </summary>
        public static string message_register_message {
            get {
                return ResourceManager.GetString("message.register_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend again.
        /// </summary>
        public static string message_resend_again {
            get {
                return ResourceManager.GetString("message.resend_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend One Time Password.
        /// </summary>
        public static string message_resend_otp {
            get {
                return ResourceManager.GetString("message.resend_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retry..
        /// </summary>
        public static string message_retry {
            get {
                return ResourceManager.GetString("message.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your review (optional).
        /// </summary>
        public static string message_review {
            get {
                return ResourceManager.GetString("message.review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your experience&apos;s feedback..
        /// </summary>
        public static string message_review_description {
            get {
                return ResourceManager.GetString("message.review_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Submitted!.
        /// </summary>
        public static string message_review_submitted {
            get {
                return ResourceManager.GetString("message.review_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to refresh this page and lose all your existing session history. 
        ///
        ///Do you want to continue and refresh the page?.
        /// </summary>
        public static string message_session_restart_confirmation_message {
            get {
                return ResourceManager.GetString("message.session_restart_confirmation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to connect again..
        /// </summary>
        public static string message_socket_disconnect_msg {
            get {
                return ResourceManager.GetString("message.socket_disconnect_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, servers are taking longer than usual..
        /// </summary>
        public static string message_taking_longer {
            get {
                return ResourceManager.GetString("message.taking_longer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re temporarily down.
        /// </summary>
        public static string message_temporarily_down {
            get {
                return ResourceManager.GetString("message.temporarily_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing high user volume at the moment, please try logging in after some time.
        /// </summary>
        public static string message_temporarily_down_description {
            get {
                return ResourceManager.GetString("message.temporarily_down_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait before resending OTP.
        /// </summary>
        public static string message_wait_resending_otp {
            get {
                return ResourceManager.GetString("message.wait_resending_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Kisan-eMitra! I am your personal assistant. Please let me know how can I help you?         ///        ///        ///        ///
        ///&lt;br&gt;You may select your preferred language..
        /// </summary>
        public static string message_welcome_greeting {
            get {
                return ResourceManager.GetString("message.welcome_greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disliked the response.
        /// </summary>
        public static string toast_reaction_dislike {
            get {
                return ResourceManager.GetString("toast.reaction_dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully liked the response.
        /// </summary>
        public static string toast_reaction_like {
            get {
                return ResourceManager.GetString("toast.reaction_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the response.
        /// </summary>
        public static string toast_reaction_reset {
            get {
                return ResourceManager.GetString("toast.reaction_reset", resourceCulture);
            }
        }
    }
}
